---


- hosts: goonie-mng
  remote_user: root
  gather_facts: yes
  roles:
    - goonie-uninstall
    - goonie-em
    - goonie-db-ha
    - goonie-mng
    - goonie-keepalive

- hosts: goonie-em
  remote_user: root
  gather_facts: yes
  roles:
    - goonie-em

- hosts: goonie1
  remote_user: root
  gather_facts: yes
  roles:
    - goonie-data 
