---

- hosts: goonie-mng
  remote_user: root
  gather_facts: yes
  roles:
    - {role: goonie, ENABLE_MNG: true}

- hosts: goonie-em
  remote_user: root
  gather_facts: yes
  roles:
    - {role: goonie, ENABLE_MNG: false}


