---

- hosts: goonie-mng
  remote_user: root
  gather_facts: yes
  vars:
    mysql_user: root
    mysql_passwrod: kx_goonie_#$%
  roles:
    - goonie-em
    - goonie-mng

- hosts: goonie-em
  remote_user: root
  gather_facts: yes
  roles:
    - goonie-em


