---

- name: Install packages in goonie em node
  package:
    name: goonie-em
    state: present
  notify: restart em

- name: systemctl disable goonie-mng
  systemd:
    name: goonie-em
    enabled: yes

