---

- name: Install packages in goonie em node
  package:
    name: goonie-em
    state: latest
  notify: restart em

- name: systemctl enable goonie-em
  systemd:
    name: goonie-em
    enabled: yes

