---

- name: packages in goonie em node
  package:
    name: goonie-em
    state: absent

- name: Install packages in goonie em node
  package:
    name: goonie-em
    state: present

- name: Add rc.local
  shell: if [ -z "`grep sysstart.sh /etc/rc.local`" ];then sed -i '2 i/usr/local/sbin/sysstart.sh' /etc/rc.local ;fi

