---

- name: stop MNG use shell
  shell: if [ -f /opt/goonie-MNG/bin/shutdown.sh ];then /opt/goonie-MNG/bin/shutdown.sh;fi

- name: packages in goonie mng node
  package:
    name: goonie-mng
    state: absent

- name: Install packages in goonie mng node
  package:
    name: goonie-mng
    allow_unauthenticated: yes
    state: present

- name: Restart goonie mng
  systemd:
    name: goonie-mng
    state: restarted

- name: set node goonie mng
  shell: neucli3 device set character=mng_master

