---


- name: judge a file or dir is exits
  shell: ls /opt/goonie-EM-bak
  ignore_errors: True
  register: result

- name: stop EM use shell
  when: result is succeeded
  shell: if [ -f /opt/goonie-EM/bin/shutdown.sh ];then /opt/goonie-EM/bin/shutdown.sh;fi

- name: delete new back packages in goonie em 
  when: result is succeeded
  file:
    path: /opt/goonie-EM
    state: absent

- name: delete new back packages in goonie neucli 
  when: result is succeeded
  file:
    path: /usr/local/sbin
    state: absent

#- name: create back packages in goonie em node
#  file:
#    path: /opt/goonie-EM-bak
#    state: directory
#
#- name: back packages in goonie em node
#  copy:
#    src: /opt/goonie-EM
#    dest: /opt/goonie-EM-bak
#    directory_mode: yes
#    remote_src: yes

- name: rollback packages in goonie em 
  when: result is succeeded
  shell: mv /opt/goonie-EM-bak /opt/goonie-EM

- name: rollback packages in goonie neucli
  when: result is succeeded
  shell: cp -r /usr/local/sbin-bak /usr/local/sbin

- name: stop MNG use shell
  when: result is succeeded
  shell: if [ -f /opt/goonie-EM/bin/startup.sh ];then /opt/goonie-EM/bin/startup.sh;fi

