---

#- name: stop goonie mng
#  systemd:
#    name: goonie-mng
#    state: stopped



- name: stop MNG use shell
  shell: if [ -f /opt/goonie-MNG/bin/shutdown.sh ];then /opt/goonie-MNG/bin/shutdown.sh;fi

- name: revert old back sql file
  package:
    path: goonie-mng
    #purge: yes
    state: absent

- name: delete old back packages in goonie mng node
  file:
    path: /opt/goonie-MNG
    state: absent


#- name: create back packages in goonie mng node
#  file:
#    path: /opt/goonie-MNG-bak
#    state: directory
#
#- name: back packages in goonie mng node
#  copy:
#    src: /opt/goonie-MNG
#    dest: /opt/goonie-MNG-bak
#    directory_mode: yes
#    rmngote_src: yes

- name: back packages in goonie mng node
  shell: cp -r /opt/goonie-MNG-bak /opt/goonie-MNG

