---

- set_fact:
    MESSAGE:
      - "=========================================="
      - "   Backup Goonie MNG Node        "
      - "=========================================="

- debug: var=MESSAGE

- import_tasks: backup_goonie_mng.yml

- import_tasks: backup_goonie_db.yml

