---


- name: Restore database
  mysql_db:
    name: all
    state: import
    target: /opt/goonie-MNG/sql/create-all.sql
  when: groups['goonie-mng'].index(inventory_hostname) == 0
  notify: restart mng



