---

#- name: stop goonie mng node
#  systemd:
#    name: goonie-mng
#    state: stopped

- name: mysql 0.0.0.0
  shell: sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: restart sql

- name: Restore database
  mysql_db:
    name: all
    login_user: root
    login_password: kx_goonie_#$%
    state: import
    target: /opt/goonie-MNG/sql/create-all.sql
  notify: restart mng



