---

- name: Install packages in goonie mng node
  package:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
  - goonie-mng
  - cetusfs

- name: systemctl disable goonie-mng
  systemd:
    name: goonie-mng
    enabled: no

