---

#- name: packages in goonie mng node
#  package:
#    name: goonie-mng
#    state: absent

- name: Install packages in goonie mng node
  package:
    name: goonie-mng
    state: present
  notify: restart mng

- name: set node goonie mng
  shell: neucli3 device set character=mng_master

