---


- name: Install packages in goonie mng node
  package:
    name: goonie-mng
    state: present
  notify: restart mng

- name: systemctl disable goonie-mng
  systemd:
    name: goonie-mng
    enabled: no

