---

- name: Install packages in goonie node
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
  - keepalived

- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted



